// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsKKVjEBhkhW_ZF24tnXtX67LI7zouu68',
    appId: '1:480354966438:web:343b199002e5c9d1c88d67',
    messagingSenderId: '480354966438',
    projectId: 'dev-iaa-ts1',
    authDomain: 'dev-iaa-ts1.firebaseapp.com',
    storageBucket: 'dev-iaa-ts1.appspot.com',
    measurementId: 'G-8J6ZPJCPWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-owJp4T30qp4YP4DS2LyMSLDjkX6prcE',
    appId: '1:480354966438:android:cdc69cd6a884053dc88d67',
    messagingSenderId: '480354966438',
    projectId: 'dev-iaa-ts1',
    storageBucket: 'dev-iaa-ts1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEkc28cxlD8kr82sfjr_TOwLFws837eJg',
    appId: '1:480354966438:ios:e239c1a17ae26c81c88d67',
    messagingSenderId: '480354966438',
    projectId: 'dev-iaa-ts1',
    storageBucket: 'dev-iaa-ts1.appspot.com',
    iosClientId: '480354966438-9col9lc1hhnhld0co2d37a8ro5a6o46a.apps.googleusercontent.com',
    iosBundleId: 'com.airasia.tsOne',
  );
}
